services:
  default-react-ts-tw:
    build:
      context: ..
      dockerfile: default-react-ts-tw/Dockerfile
    volumes:
      - ..:/workspaces/ReactTS-Showcases:cached
      - /workspaces/ReactTS-Showcases/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"

  notes-app-1:
    build:
      context: ..
      dockerfile: notes-app-1/Dockerfile
    volumes:
      - ..:/workspaces/ReactTS-Showcases:cached
      - /workspaces/ReactTS-Showcases/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"

  tasks-app-1:
    build:
      context: ..
      dockerfile: tasks-app-1/Dockerfile
    volumes:
      - ..:/workspaces/ReactTS-Showcases:cached
      - /workspaces/ReactTS-Showcases/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"

  footballer-app-1:
    build:
      context: ..
      dockerfile: footballer-app-1/Dockerfile
    volumes:
      - ..:/workspaces/ReactTS-Showcases:cached
      - /workspaces/ReactTS-Showcases/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"

  tic-tac-toe-app-1:
    build:
      context: ..
      dockerfile: tic-tac-toe-app-1/Dockerfile
    volumes:
      - ..:/workspaces/ReactTS-Showcases:cached
      - /workspaces/ReactTS-Showcases/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"

  tests-app-1:
    build:
      context: ..
      dockerfile: tests-app-1/Dockerfile
    volumes:
      - ..:/workspaces/ReactTS-Showcases:cached
      - /workspaces/ReactTS-Showcases/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"
